/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*Includes -------------------------------------------------------*/
#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "delay.h"
#include "defines.h"
/*Macro defines --------------------------------------------------*/
/**
 * @brief para seleccionar el medio de transmision para el printf
 * 0: USART
 * 1: SW0
 */
#define USE_SW0			1
#define TIM2_CH1		A, 5
#define TIM2_CH2		A, 1

/*Global variables -----------------------------------------------*/

/*Function prototypes --------------------------------------------*/



int main(void)
{
	//enable clock
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	RCC->AHB1ENR |= GPIOX_CLOCK(TIM2_CH1);
	/*configuracion de pines para el timer2*/
	GPIOX_MODER(MODE_ALTER, TIM2_CH1);
	GPIOX_MODER(MODE_ALTER, TIM2_CH2);
	GPIOX_AFR(1, TIM2_CH1);
	GPIOX_AFR(1, TIM2_CH2);
	GPIOX_OSPEEDR(MODE_SPD_VHIGH, TIM2_CH1);		//Very high speed
	GPIOX_OSPEEDR(MODE_SPD_VHIGH, TIM2_CH2);
	//configuracion del timer
	TIM2->CR1 = 0;
	TIM2->ARR = 0xFFFFFFFFU;
	TIM2->PSC = 0;
	//configuracion del canal o los modos captura y comparacion
	//Los canales como entrada
	TIM2->CCMR1 = TIM_CCMR1_CC1S_0;					//TI1FP1 mapped on TI1 (PA5)
	TIM2->CCMR1 |= TIM_CCMR1_CC2S_0;				//TI1FP2 mapped on TI2 (PA1)
	//configurar la polaridad
	TIM2->CCER = 0;
	/*external clock mode 1*/
	//MODO ENCODER
	TIM2->SMCR |= TIM_SMCR_SMS_1 | TIM_SMCR_SMS_0;	//Encoder mode 3

	//habilitar el conteo
	TIM2->CR1 |= TIM_CR1_CEN;
	//delay init
	delay_init();
    /* Loop forever */
	for(;;){
		printf("CONTADOR->%lu ",TIM2->CNT);
		printf("SENTIDO: ");
		printf(TIM2->CR1 & TIM_CR1_DIR ? "IZQUIERDO\r\n":"DERECHO\r\n");

		delay_ms(1000);
	}
}
/*Function definition ------------------------------------------------*/
/**********************************************************************/

int __io_putchar(int ch){
#if (USE_SW0 == 1)
	ITM_SendChar(ch);
#else
	//todo

#endif
	return ch;
}
