/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*Includes -------------------------------------------------------*/
#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
/*Macro defines --------------------------------------------------*/
/**
 * @brief para seleccionar el medio de transmision para el printf
 * 0: USART
 * 1: SW0
 */
#define USE_SW0			1

#define LED				5			//PA5
#define SW				13			//PC13
/*Global variables -----------------------------------------------*/

/*Function prototypes --------------------------------------------*/

uint8_t sw;

int main(void)
{
	//HABILITAR EL RELOJ
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOCEN;
	//MODER
	//PC13->ENTRADA
	GPIOC->MODER &=~ (GPIO_MODER_MODE13); 		//MODO ENTRADA
//	GPIOC->PUPDR &=~ (GPIO_PUPDR_PUPD13);		//RESET
//	GPIOC->PUPDR |= GPIO_PUPDR_PUPD13_0;		//PULL UP
	//PA5->SALIDA
	GPIOA->MODER &=~ (GPIO_MODER_MODE5);
	GPIOA->MODER |= GPIO_MODER_MODE5_0;			//SALIDA
	GPIOA->OTYPER &=~ GPIO_OTYPER_OT5;			//PUSH PULL
	GPIOA->OSPEEDR |= GPIO_OSPEEDR_OSPEED5;		//VERY HIGH SPEED
	GPIOA->PUPDR &=~ GPIO_PUPDR_PUPD5;			//NO PULL UP / DOWN
    /* Loop forever */
	for(;;){
		sw = GPIOC->IDR>>13 & 0x1;
		if(sw == 0){							//PRESED
			while(!(GPIOC->IDR & 0x1<<13));    	//RELEASED
			GPIOA->ODR |= 1U<<5;
			//GPIOA->BSRR |= 1U<<5;
		}else{
			GPIOA->ODR &=~ (1U<<5);
			//GPIOA->BSRR |= 1U<<(16+5);
		}
	}
}
/*Function definition ------------------------------------------------*/
/**********************************************************************/

int __io_putchar(int ch){
#if (USE_SW0 == 1)
	ITM_SendChar(ch);
#else
	//todo

#endif
	return ch;
}
