/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include "Config.h"
#include "delay_tim.h"
#include "RCC.h"




#define TIM2_PSC			16E+6
#define psc					0

/**
 * @brief generacion de IT cada 50ms
 */
void TIM2_ITConfig(uint32_t freq);


int main(void)
{
	flash_cofig();
	PLL_Config();
/****************************************/
	RCC->AHB1ENR |= GPIOX_CLOCK(LED);
	GPIOX_MODER(MODE_OUT,LED);
/****************************************/
	//TIM2_ITConfig(20);
	delay_Init();
    /* Loop forever */
	for(;;){
		GPIOX_ODR(LED) ^=1U;
		delay_ms(50);
	}
}

/**
 * @brief generacion de IT cada 50ms
 */
void TIM2_ITConfig(uint32_t freq){//timer de 32-bits
	uint32_t tmp;
	/*habilitar el reloj*/
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	/*configurar el timer para la generacion de IT*/
	/**
	 * Fclock_psc = 16MHz
	 * PSC = 1
	 * ARR ?
	 * ARR = Fclock_psc/((PSC+1)*UpdateEvent) - 1
	 * ARR = 16MHz/((4)*1000) - 1
	 * ARR = 4000 - 1
	 */
	tmp = TIM2_PSC /((psc + 1) * freq) - 1 ; 		//valor de ARRR
	/*deshabilitado*/
	TIM2->CR1 &=~ (TIM_CR1_CEN);

	TIM2->ARR = tmp;
	TIM2->PSC = psc;

	/*interrupciones*/
	TIM2->DIER |= TIM_DIER_UIE;

	NVIC_EnableIRQ(TIM2_IRQn);						//habilita la IT para el timer2

	/*habilita el conteo del timer*/
	TIM2->CR1 |= TIM_CR1_CEN;
	return;
}


void TIM2_IRQHandler(void){
	if(TIM2->SR & TIM_SR_UIF){
		//CLEAR
		TIM2->SR &=~ TIM_SR_UIF;
/****************************************************/
		GPIOX_ODR(LED) ^= 1U;

	}


	return;
}
