/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*Includes -------------------------------------------------------*/
#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "delay_it.h"
#include "defines.h"
#include "stdarg.h"
#include <stdbool.h>
#include "circularbuffer.h"
#include "circularuart.h"
#include <string.h>
/*Macro defines --------------------------------------------------*/
/**
 * @brief para seleccionar el medio de transmision para el printf
 * 0: USART
 * 1: SW0
 */
#define USE_SW0			0
#define REDB        "\033[1;31m"
#define GREENB      "\033[1;32m"
#define YELLOWB     "\033[1;33m"
#define BLUEB       "\033[1;34m"
#define MAGENTAB    "\033[1;35m"
#define CYANB       "\033[1;36m"
#define WHITEB      "\033[1;37m"

#define RED         "\033[0;31m"
#define GREEN       "\033[0;32m"
#define YELLOW      "\033[0;33m"
#define BLUE        "\033[0;34m"
#define MAGENTA     "\033[0;35m"
#define CYAN        "\033[0;36m"
#define WHITE       "\033[0;37m"
#define DEFAULT_COLOR     "\033[0;39;49m"
#define SERIAL_PRINTLN(...) {printf(__VA_ARGS__);\
						     printf("\r\n");}
#define SERIAL_PRINT(...) 	{printf(__VA_ARGS__);}

#define SERIAL_PRINTCOLOR(COLOR, ...) {SERIAL_PRINT(COLOR); \
										SERIAL_PRINT(__VA_ARGS__);\
										SERIAL_PRINT("\033[0;39;49m");}
/*Global variables -----------------------------------------------*/
uint8_t txbuffer[128];
uint8_t rxbuffer[128];
uint8_t _txbuffer[128];
uint8_t _rxbuffer[128];
/*Function prototypes --------------------------------------------*/

void suma(int length, ...);

int main(void)
{
	RCC->AHB1ENR |= GPIOX_CLOCK(LED);
	GPIOX_MODER(MODE_OUT, LED);
	//delay init
	delay_init_it();
	//UART2 PINOUT
	RCC->AHB1ENR |= GPIOX_CLOCK(UART2_TX);
	GPIOX_MODER(MODE_ALTER, UART2_TX);
	GPIOX_MODER(MODE_ALTER, UART2_RX);
	GPIOX_AFR(7U, UART2_TX);
	GPIOX_AFR(7U, UART2_RX);
	//UART2
	RCC->APB1ENR |= RCC_APB1ENR_USART2EN;
	//Deshabilitar
	USART2->CR1 = 0;
	USART2->CR1 |= USART_CR1_TE | USART_CR1_RE; //habilita la recepcion y la transmision
	/**
	 * baud = 115200
	 * USARTDIV  =16MHz/(16 * 115200)
	 * USARTDIV = 8.6805
	 * DIV_Mantisa = 0x8
	 * DIV_Fraction = 16 * 0.6806 ~  = B
	 * BRR = DIV_Mantisa<<4 | DIV_Fraction
	 * BRR = 0x8B
	 */
	USART2->BRR = 0x8B;
	USART2->CR1 |= USART_CR1_UE;
	//CONFIGURACIN DE LA IT
	/*local*/
	USART2->CR1 |= USART_CR1_RXNEIE;		//habilita la IT para la recepción
	/*global*/
	NVIC_EnableIRQ(USART2_IRQn);			//Habilita la IT en la NVIC
	NVIC_SetPriority(USART2_IRQn, 2);		//cambia la prioridad
	//todo
	SERIAL_PRINTLN("CONFIGURACION CORRECTA");
	CircularUART2_Init();
	CircularUART_StartTx(txbuffer, 6);

	sprintf((char*)_txbuffer, "hola mundo desde buffer circular\r\n");
	CircularUART_Send(_txbuffer, strlen((char*)txbuffer));
	CircularUART_StartRx(rxbuffer, 7);

	CircularUART_Receive(_rxbuffer, 7);
    /* Loop forever */

	for(;;){

	}
}
/*Function definition ------------------------------------------------*/
/**********************************************************************/

int __io_putchar(int ch){
#if (USE_SW0 == 1)
	ITM_SendChar(ch);
#else
	//todo
	uint8_t c = ch & 0xFF;
	while(!(USART2->SR & USART_SR_TXE));
	USART2->DR = c;
#endif
	return ch;
}
#if USE_SW0 == 0
int __io_getchar(void){
	while(!(USART2->SR & USART_SR_RXNE));
	return USART2->DR;
}
#endif
