/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*Includes -------------------------------------------------------*/
#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "delay.h"
#include "defines.h"
#include "HD44780.h"
/*Macro defines --------------------------------------------------*/
/**
 * @brief para seleccionar el medio de transmision para el printf
 * 0: USART
 * 1: SW0
 */
#define USE_SW0			1
#define __weak __attribute__((weak))
/*Global variables -----------------------------------------------*/
uint32_t count;
/*Function prototypes --------------------------------------------*/

void EXTI_ApplicationCallback(uint32_t pinnumber);
void EXIT_IRQHandling(uint32_t pin_number);


int main(void)
{
	RCC->AHB1ENR |= GPIOX_CLOCK(LED);
	GPIOX_MODER(MODE_OUT, LED);
	//CONFIGURACION DEL PIN
	RCC->AHB1ENR |= GPIOX_CLOCK(BUTTON);
	GPIOX_MODER(MODE_DIGITAL_INPUT, BUTTON);
	//CONFIGURACION DE LA LINEA
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
	//CONFIGURACION LOCAL
	/*1. habilitar el bit de enmascaramiento*/
	EXTI->IMR |= EXTI_IMR_IM13;
	/*2. seleccionar el borde de disparo de la IT*/
	EXTI->FTSR |= EXTI_FTSR_TR13;					//IT para exti13 flanco decendente
	/*3. asignar el pin a al linea EXTI1*/
	SYSCFG->EXTICR[3] &=~ SYSCFG_EXTICR4_EXTI13;	//clear
	SYSCFG->EXTICR[3] |= SYSCFG_EXTICR4_EXTI13_PC;	//PC13
	//CONFIGURACION GLOBAL O CONFIGURACION EN LA NVIC
	//PRIORIDAD
	NVIC_SetPriority(EXTI15_10_IRQn, 3);
	//HABILITAR LA IT
	NVIC_EnableIRQ(EXTI15_10_IRQn);


	//delay init
	delay_init();

	//LCD INIT
	LCD_Init(20, 4);
	LCD_Printf(0, 0, "INTERRUPCIONES\r\nEXTERNAS");
    /* Loop forever */
	for(;;){
		//ODR5 = 1;
		GPIOX_ODR(LED) = 1;
		delay_ms(50);
		//ODR5 = 0;
		GPIOX_ODR(LED) = 0;
		delay_ms(50);
	}
}
/*Function definition ------------------------------------------------*/
void EXIT_IRQHandling(uint32_t pin_number){
	//CLEAR
	EXTI->PR |= 1U<<pin_number;
	EXTI_ApplicationCallback(pin_number);
}



void EXTI_ApplicationCallback(uint32_t pinnumber){
	if(pinnumber == GPIOX_PIN(BUTTON)){
		//TODO
		count += 1;
		LCD_Printf(0, 3, "             ");
		LCD_Printf(0, 3, "COUNT:%d",count);
	}
	return;
}
/**********************************************************************/

int __io_putchar(int ch){
#if (USE_SW0 == 1)
	ITM_SendChar(ch);
#else
	//todo

#endif
	return ch;
}
